# .github/actions/setup-node-env/action.yml
name: setup-node-env
description: Setup Node and install deps (npm ci)
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install deps
      shell: bash
      run: npm ci --no-audit --no-fund
